Remove GitHub Actions failure test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,8 +33,8 @@ jobs:
 
             echo "[+] Deploy complete."
 
-            echo "[TEST] Intentionally failing GitHub Action..."
-            exit 1
+            # echo "[TEST] Intentionally failing GitHub Action..."
+            # exit 1
 
       - name: Notify Discord on failure
         if: failure()
